######################################################################
##
## Filename: ad9228tb.udo
## Created on: Tue Mar 22 12:29:37 PM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
