######################################################################
##
## Filename: ad9228Input.udo
## Created on: Fri May 20 9:01:26 AM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
