######################################################################
##
## Filename: alu.udo
## Created on: Tue Apr 19 3:57:24 PM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
