######################################################################
##
## Filename: ClkEn_Gen.udo
## Created on: Wed May 18 3:06:56 PM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
