######################################################################
##
## Filename: displayIntf.udo
## Created on: Mon Aug 22 1:15:49 PM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
