######################################################################
##
## Filename: FADCSpi.udo
## Created on: Mon Jun 20 2:09:09 PM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
