######################################################################
##
## Filename: FastChannel.udo
## Created on: Fri Jun 24 9:41:39 AM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
