######################################################################
##
## Filename: FaultGen.udo
## Created on: Wed Apr 06 2:20:17 PM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
