######################################################################
##
## Filename: flow_intf.udo
## Created on: Tue Jul 19 1:11:40 PM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
