######################################################################
##
## Filename: FocusCoil.udo
## Created on: Wed Mar 16 1:11:37 PM Pacific Standard Time (Mexico) 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
