######################################################################
##
## Filename: ModCmd.udo
## Created on: Thu Mar 24 1:52:58 PM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
