######################################################################
##
## Filename: Mon_ADC_Cntl.udo
## Created on: Wed May 18 3:46:53 PM Pacific Daylight Time 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
