######################################################################
##
## Filename: Trigger.udo
## Created on: Thu Mar 10 2:58:19 PM Pacific Standard Time (Mexico) 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
